### ISSUE TITLE
smt fails with cljstyle-0.16.626.jar manifest does not specify Main-Class

### ISSUE THREAD

**Issue by jayvdb** [py2many/py2many#581]
https://github.com/py2many/py2many/actions/runs/7441257838/job/20243161234?pr=580

```rust
Inferring main class from manifest of cljstyle-RELEASE.jar using glob \'cljstyle-*.jar\'\nTraceback (most recent call last):\n  File "/home/runner/work/py2many/py2many/.tox/py39/bin/jgo", line 8, in <module>\n    sys.exit(main())\n  File "/home/runner/work/py2many/py2many/.tox/py39/lib/python3.9/site-packages/jgo/jgo.py", line 402, in _jgo_main\n    completed_process = run(parser, argv=argv, stdout=stdout, stderr=stderr)\n  File "/home/runner/work/py2many/py2many/.tox/py39/lib/python3.9/site-packages/jgo/jgo.py", line 788, in run\n    return _run(\n  File "/home/runner/work/py2many/py2many/.tox/py39/lib/python3.9/site-packages/jgo/jgo.py", line 846, in _run\n    raise NoMainClassInManifest(jar_path)\njgo.jgo.NoMainClassInManifest: /home/runner/.jgo/mvxcvi/cljstyle/RELEASE/9f9c16b38989fc2b103f1ca663d00a8e6946595a60d5dfc371f3face3050f4f4/cljstyle-0.16.626.jar manifest does not specify Main-Class\n'b''
```

**Comment by jayvdb** [comment]
raised upstream as https://github.com/greglook/cljstyle/issues/105

**Comment by jayvdb** [comment]
fixed in https://github.com/py2many/py2many/pull/580
